### PR TITLE
refactor: API

### PR DESCRIPTION
**Pull request by zameji**
This escalated a bit, main changes:

1. Updated psycopg from 2 to 3
2. type hints in most places
3. Pre-commit for consistent formatting 
4. Restructured code to separate concerns
5. Added input validation with Pydantic, allowing to drop the ALLOWED_ checks
6. Restructured query, some primitive optimization (still on my end with a sample query a speedup of factor 1.7x)
7. Prepared server-side pagination (though some API change would be useful to better support it in frontend, but would take this to separate PR implementing just pagination in front- and backend)

### CODE REVIEW

**Comment by zameji** [comment]
This also addresses #3 (via enabled / disabled paging) and implements #4.

**Comment by zameji** [comment]
Also migrated to Vue3 (as Vue2 is EoL for a while now).
Did also major changes to the UI:
* better support for horizontal screens - seeing the main map and results at once should work for most resolutions
* more compact feature selection
* individual features may be renamed to keep track of them while searching
* pagination with prefetching the next batch in the background
* results may be removed from the list (allowing discarding candidates that are clear false positives)
* better performance on low-end computers even for larger queries
* dark mode (got this one for free with the upgrade to vue/vuetify3)

Backend changes
* Return geometries (addresses #5)
* Handle multiple instances of same feature correctly (i.e. not returning duplicates)

There are still some TODOs open:
* Modularize the store to properly use Pinia
* The OneTap-Login was dropped for now

@loganwilliams Some further UX improvements seem possible to me, but would require knowing more about how it's used - e.g. do people use the small previews more than the main map?

**Comment by loganwilliams** [comment]
Thanks for this @zameji, really appreciate your work here. It will take me some time to review it, and I might ask you to break the PR into smaller feature specific chunks. I'll be in touch soon.

Best,
Logan

**Comment by zameji** [comment]
Sure, take your time. Breaking it up is going to be somewhat problematic though, esp. in the frontend, since the migration to Vue3 brought with it a lot of necessary changes.
In the backend, the individual commits should be smaller and easier to review by itself.
If you have any questions/doubts about the design decisions, let me know - I'm open to trying different approaches.

**Comment by loganwilliams** [comment]
Thanks @zameji, I understand that it might be hard to break up changes. As a first pass, to separate PR concerns, could you make one PR for front-end changes and one PR for back-end changes?

**Comment by zameji** [comment]
Sure @loganwilliams I'll look into that tonight / tomorrow night.
The current frontend can't work with the new backend without a small change, though, because the interface changed. I'll include that change in the backend PR.

**Comment by zameji** [comment]
Closing this PR as:

- #8 has the frontend part
- #9 has the backend (and a small change to make the frontend support both backends)

**Pull request closed without merging**
